File badges
fliegwerk/mediacenter pull request #4
Opened 2020-07-18 13:59 UTC by fussel178

Added nice file badges to video description:
![Screenshot_20200718_155647](https://user-images.githubusercontent.com/52416718/87854091-b9a3f580-c8fe-11ea-9fc3-74e17edc468a.png)

2020-07-18 14:08 UTC, pklaschka requested changes
Thank you for the PR. Please see my inline comments.

BTW: It might be useful to call `sd-576p` `pal-576p`, as this is basically the PAL standard. NTSC, on the other hand, would (of course) be `480p`. I'd suggest that we support both formats 😉

2020-07-18 14:08 UTC, pklaschka commented on README.md
> +The badges array will be parsed to vector graphics equally named in the `badges` folder.
Could you please add a few more details about the naming, here? something like

```suggestion
The `badges` array contains the file names (without extension) that are stored as `[name].svg` in the `badges` directory. `"hd-720p"`, for example, would render the file `badges/hd-720p`.
```

2020-07-18 14:08 UTC, pklaschka commented on index.php
> +                        echo "<!-- Invalid badge: $badge, file not found: $path -->";
We need to escape this as well:

```suggestion
                        echo "<!-- Invalid badge: " . htmlspecialchars($badge) . ", file not found: " . htmlspecialchars($path) . " -->";
```

2020-09-15 08:26 UTC, fussel178 commented
> BTW: It might be useful to call `sd-576p` `pal-576p`, as this is basically the PAL standard. NTSC, on the other hand, would (of course) be `480p`. I'd suggest that we support both formats wink

Good call!
I forgot the names for the resolutions.

2022-01-28 19:20 UTC, pklaschka approved these changes
This has been in my code review backlog for too long. Let's merge this for now and if we want, we can improve on that later :see_no_evil:

2022-01-29 10:33 UTC, fussel178 commented
Well, I tried to create the `pal-576p` and `ntsc-480p` badges. But I currently don't have AdobeXD to open the design file. :see_no_evil:

2022-01-30 18:35 UTC, pklaschka reviewed
Let's merge this for now and add the new Icons later :wink:

![movefast](https://graphite-user-uploaded-assets.s3.amazonaws.com/default-memes/movefast.gif)

2022-01-31 00:11 UTC, merged